// Code generated by protoc-gen-go.
// source: agent.proto
// DO NOT EDIT!

/*
Package agent is a generated protocol buffer package.

It is generated from these files:
	agent.proto

It has these top-level messages:
	LchRequest
	LchReply
	AppInfo
	Process
	ProcRequest
	ProcList
	RegReply
	DeregRequest
	DeregReply
*/
package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LchRequest struct {
	// Application's id
	AppId string `protobuf:"bytes,1,opt,name=AppId,json=appId" json:"AppId,omitempty"`
	// Executable binary's name
	ExecName string `protobuf:"bytes,2,opt,name=ExecName,json=execName" json:"ExecName,omitempty"`
	// Arguments of execution
	ExecArgs []string `protobuf:"bytes,3,rep,name=ExecArgs,json=execArgs" json:"ExecArgs,omitempty"`
	// Flag indicating if enalble application monitoring
	Moni bool `protobuf:"varint,4,opt,name=Moni,json=moni" json:"Moni,omitempty"`
}

func (m *LchRequest) Reset()                    { *m = LchRequest{} }
func (m *LchRequest) String() string            { return proto.CompactTextString(m) }
func (*LchRequest) ProtoMessage()               {}
func (*LchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LchReply struct {
}

func (m *LchReply) Reset()                    { *m = LchReply{} }
func (m *LchReply) String() string            { return proto.CompactTextString(m) }
func (*LchReply) ProtoMessage()               {}
func (*LchReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AppInfo struct {
	// Application's id
	Id string `protobuf:"bytes,1,opt,name=Id,json=id" json:"Id,omitempty"`
	// Framework used
	Frameworks []string `protobuf:"bytes,2,rep,name=Frameworks,json=frameworks" json:"Frameworks,omitempty"`
	// The JobIds given by corresponding frameworks
	JobIds []string `protobuf:"bytes,3,rep,name=JobIds,json=jobIds" json:"JobIds,omitempty"`
	// Process pattern used to match processes
	Pattern string `protobuf:"bytes,4,opt,name=Pattern,json=pattern" json:"Pattern,omitempty"`
	// Pid of the application's main process.
	// If it's set, then the process on the same node as
	// the target agent, otherwise not.
	Pid int64 `protobuf:"varint,5,opt,name=Pid,json=pid" json:"Pid,omitempty"`
}

func (m *AppInfo) Reset()                    { *m = AppInfo{} }
func (m *AppInfo) String() string            { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()               {}
func (*AppInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Process struct {
	// Process's operating system pid
	Pid int64 `protobuf:"varint,1,opt,name=Pid,json=pid" json:"Pid,omitempty"`
	// Process name
	Name string `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	// Command line to run the process
	Cmd string `protobuf:"bytes,3,opt,name=Cmd,json=cmd" json:"Cmd,omitempty"`
}

func (m *Process) Reset()                    { *m = Process{} }
func (m *Process) String() string            { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()               {}
func (*Process) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ProcRequest struct {
	AppId string `protobuf:"bytes,1,opt,name=AppId,json=appId" json:"AppId,omitempty"`
}

func (m *ProcRequest) Reset()                    { *m = ProcRequest{} }
func (m *ProcRequest) String() string            { return proto.CompactTextString(m) }
func (*ProcRequest) ProtoMessage()               {}
func (*ProcRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ProcList struct {
	Procs []*Process `protobuf:"bytes,1,rep,name=Procs,json=procs" json:"Procs,omitempty"`
}

func (m *ProcList) Reset()                    { *m = ProcList{} }
func (m *ProcList) String() string            { return proto.CompactTextString(m) }
func (*ProcList) ProtoMessage()               {}
func (*ProcList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ProcList) GetProcs() []*Process {
	if m != nil {
		return m.Procs
	}
	return nil
}

// Reply message of Register()
//
type RegReply struct {
}

func (m *RegReply) Reset()                    { *m = RegReply{} }
func (m *RegReply) String() string            { return proto.CompactTextString(m) }
func (*RegReply) ProtoMessage()               {}
func (*RegReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// Request message of Deregister()
type DeregRequest struct {
	// Application's Id
	AppId string `protobuf:"bytes,1,opt,name=AppId,json=appId" json:"AppId,omitempty"`
}

func (m *DeregRequest) Reset()                    { *m = DeregRequest{} }
func (m *DeregRequest) String() string            { return proto.CompactTextString(m) }
func (*DeregRequest) ProtoMessage()               {}
func (*DeregRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// Reply message of Deregister()
type DeregReply struct {
}

func (m *DeregReply) Reset()                    { *m = DeregReply{} }
func (m *DeregReply) String() string            { return proto.CompactTextString(m) }
func (*DeregReply) ProtoMessage()               {}
func (*DeregReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*LchRequest)(nil), "agent.LchRequest")
	proto.RegisterType((*LchReply)(nil), "agent.LchReply")
	proto.RegisterType((*AppInfo)(nil), "agent.AppInfo")
	proto.RegisterType((*Process)(nil), "agent.Process")
	proto.RegisterType((*ProcRequest)(nil), "agent.ProcRequest")
	proto.RegisterType((*ProcList)(nil), "agent.ProcList")
	proto.RegisterType((*RegReply)(nil), "agent.RegReply")
	proto.RegisterType((*DeregRequest)(nil), "agent.DeregRequest")
	proto.RegisterType((*DeregReply)(nil), "agent.DeregReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for MonitorProcs service

type MonitorProcsClient interface {
	// Launch an application
	Launch(ctx context.Context, in *LchRequest, opts ...grpc.CallOption) (*LchReply, error)
	// Manager registers an application, and agent responds
	// with the app's processes' info on the node.
	Register(ctx context.Context, in *AppInfo, opts ...grpc.CallOption) (*RegReply, error)
	// Manager deregisters an application, and agent responds
	// with a success indicator.
	Deregister(ctx context.Context, in *DeregRequest, opts ...grpc.CallOption) (*DeregReply, error)
	// Manager send application info, and agent responds
	// with the app's processes' info on the node.
	GetProcesses(ctx context.Context, in *ProcRequest, opts ...grpc.CallOption) (*ProcList, error)
}

type monitorProcsClient struct {
	cc *grpc.ClientConn
}

func NewMonitorProcsClient(cc *grpc.ClientConn) MonitorProcsClient {
	return &monitorProcsClient{cc}
}

func (c *monitorProcsClient) Launch(ctx context.Context, in *LchRequest, opts ...grpc.CallOption) (*LchReply, error) {
	out := new(LchReply)
	err := grpc.Invoke(ctx, "/agent.MonitorProcs/Launch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorProcsClient) Register(ctx context.Context, in *AppInfo, opts ...grpc.CallOption) (*RegReply, error) {
	out := new(RegReply)
	err := grpc.Invoke(ctx, "/agent.MonitorProcs/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorProcsClient) Deregister(ctx context.Context, in *DeregRequest, opts ...grpc.CallOption) (*DeregReply, error) {
	out := new(DeregReply)
	err := grpc.Invoke(ctx, "/agent.MonitorProcs/Deregister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorProcsClient) GetProcesses(ctx context.Context, in *ProcRequest, opts ...grpc.CallOption) (*ProcList, error) {
	out := new(ProcList)
	err := grpc.Invoke(ctx, "/agent.MonitorProcs/GetProcesses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MonitorProcs service

type MonitorProcsServer interface {
	// Launch an application
	Launch(context.Context, *LchRequest) (*LchReply, error)
	// Manager registers an application, and agent responds
	// with the app's processes' info on the node.
	Register(context.Context, *AppInfo) (*RegReply, error)
	// Manager deregisters an application, and agent responds
	// with a success indicator.
	Deregister(context.Context, *DeregRequest) (*DeregReply, error)
	// Manager send application info, and agent responds
	// with the app's processes' info on the node.
	GetProcesses(context.Context, *ProcRequest) (*ProcList, error)
}

func RegisterMonitorProcsServer(s *grpc.Server, srv MonitorProcsServer) {
	s.RegisterService(&_MonitorProcs_serviceDesc, srv)
}

func _MonitorProcs_Launch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorProcsServer).Launch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.MonitorProcs/Launch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorProcsServer).Launch(ctx, req.(*LchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorProcs_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorProcsServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.MonitorProcs/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorProcsServer).Register(ctx, req.(*AppInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorProcs_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorProcsServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.MonitorProcs/Deregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorProcsServer).Deregister(ctx, req.(*DeregRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorProcs_GetProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorProcsServer).GetProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.MonitorProcs/GetProcesses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorProcsServer).GetProcesses(ctx, req.(*ProcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonitorProcs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.MonitorProcs",
	HandlerType: (*MonitorProcsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Launch",
			Handler:    _MonitorProcs_Launch_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _MonitorProcs_Register_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _MonitorProcs_Deregister_Handler,
		},
		{
			MethodName: "GetProcesses",
			Handler:    _MonitorProcs_GetProcesses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0xdd, 0xac, 0xf3, 0xd5, 0xd9, 0xa8, 0xb4, 0x03, 0x42, 0xd6, 0x1e, 0x50, 0x14, 0x7a, 0xc8,
	0x85, 0x15, 0x2a, 0x82, 0xfb, 0x8a, 0x2f, 0x15, 0x2d, 0x68, 0x95, 0x7f, 0x90, 0x26, 0xee, 0x36,
	0xd0, 0xd8, 0xc6, 0x76, 0x05, 0x3d, 0xf0, 0x4f, 0xf9, 0x31, 0xc8, 0x8e, 0x13, 0x02, 0x87, 0xbd,
	0xe5, 0xcd, 0x1b, 0xcf, 0x7b, 0xf3, 0x26, 0xb0, 0xaa, 0x0f, 0x8c, 0x9b, 0x8d, 0x54, 0xc2, 0x08,
	0x8c, 0x1c, 0x28, 0x38, 0xc0, 0xae, 0xb9, 0xad, 0xd8, 0xf7, 0x7b, 0xa6, 0x0d, 0x3e, 0x81, 0x68,
	0x2b, 0xe5, 0x55, 0x4b, 0x83, 0x3c, 0x28, 0x4f, 0xaa, 0xa8, 0xb6, 0x00, 0xd7, 0x90, 0xbe, 0xff,
	0xc9, 0x9a, 0x2f, 0x75, 0xcf, 0xe8, 0xd2, 0x11, 0x29, 0xf3, 0x78, 0xe4, 0xb6, 0xea, 0xa0, 0x29,
	0xc9, 0xc9, 0xc8, 0x59, 0x8c, 0x08, 0xe1, 0x67, 0xc1, 0x3b, 0x1a, 0xe6, 0x41, 0x99, 0x56, 0x61,
	0x2f, 0x78, 0x57, 0x00, 0xa4, 0x4e, 0x4f, 0xde, 0x3d, 0x14, 0xbf, 0x20, 0xb1, 0x6a, 0xfc, 0x46,
	0xe0, 0x29, 0x2c, 0x27, 0xd5, 0x65, 0xd7, 0xe2, 0x33, 0x80, 0x0f, 0xaa, 0xee, 0xd9, 0x0f, 0xa1,
	0xbe, 0x69, 0xba, 0x74, 0x83, 0xe1, 0x66, 0xaa, 0xe0, 0x53, 0x88, 0x3f, 0x89, 0xeb, 0xab, 0x76,
	0x14, 0x8d, 0xbf, 0x3a, 0x84, 0x14, 0x92, 0x7d, 0x6d, 0x0c, 0x53, 0xdc, 0xa9, 0x9e, 0x54, 0x89,
	0x1c, 0x20, 0x9e, 0x01, 0xd9, 0x77, 0x2d, 0x8d, 0xf2, 0xa0, 0x24, 0x15, 0x91, 0x5d, 0x5b, 0x6c,
	0x21, 0xd9, 0x2b, 0xd1, 0x30, 0xad, 0x47, 0x32, 0x98, 0x48, 0xeb, 0x7d, 0xb6, 0x6f, 0xc8, 0xed,
	0xae, 0x67, 0x40, 0xde, 0xf6, 0x2d, 0x25, 0xae, 0x44, 0x9a, 0xbe, 0x2d, 0x9e, 0xc3, 0xca, 0x8e,
	0x38, 0x1a, 0x5f, 0xf1, 0x12, 0x52, 0xdb, 0xb4, 0xeb, 0xb4, 0xc1, 0x0b, 0x88, 0xec, 0xb7, 0xa6,
	0x41, 0x4e, 0xca, 0xd5, 0xe5, 0xe9, 0x66, 0x38, 0x89, 0xf7, 0x51, 0x45, 0xd2, 0x92, 0x36, 0xa4,
	0x8a, 0x1d, 0x86, 0x90, 0x2e, 0x20, 0x7b, 0xc7, 0x94, 0x45, 0xc7, 0x34, 0x32, 0x00, 0xdf, 0x25,
	0xef, 0x1e, 0x2e, 0x7f, 0x07, 0x90, 0xd9, 0xe4, 0x8d, 0x50, 0x4e, 0x0d, 0x37, 0x10, 0xef, 0xea,
	0x7b, 0xde, 0xdc, 0xe2, 0xb9, 0x57, 0xfc, 0x7b, 0xf4, 0xf5, 0xa3, 0x79, 0xc9, 0x4a, 0x2e, 0xf0,
	0x85, 0x33, 0xd0, 0x69, 0xc3, 0x14, 0x8e, 0x1e, 0xfd, 0xa9, 0xa6, 0xf6, 0xc9, 0xe1, 0x02, 0xdf,
	0x78, 0xf5, 0xe1, 0xc1, 0x63, 0xdf, 0x30, 0xb7, 0xbd, 0x3e, 0xff, 0xb7, 0x38, 0xbc, 0x7b, 0x0d,
	0xd9, 0x47, 0x66, 0xfc, 0xf2, 0x4c, 0x23, 0xce, 0xe2, 0xf8, 0xdf, 0xdd, 0x18, 0x61, 0xb1, 0xb8,
	0x8e, 0xdd, 0x1f, 0xfc, 0xea, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xac, 0xb9, 0xcd, 0xd0,
	0x02, 0x00, 0x00,
}
